[tool.poetry]
name = "helix"
version = "0.1.0"
description = ""
authors = ["That Guy <timmy.anderson.aol.com@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
